sudo: false
language: node_js
node_js:
  - "4"
  - '5'
install:
  - npm install
before_script:
  - npm install -g typescript
script:
  - npm test

notifications:
  email:
    on_success: always
    on_failure: always
